  services:
  - type: web
    name: weather-api
    env: node
    plan: free
    buildCommand: cd server && npm install --build-from-source
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_VERSION
        value: 20.17.0
      - key: WEATHER_API_KEY
        value: 9dc47327f824116734111d9a56b9fbeb
      - key: PORT
        value: 5050
      - key: CACHE_TTL_CURRENT
        value: 600
      - key: CACHE_TTL_FORECAST
        value: 3600
      - key: NODE_ENV
        value: production
    disks:
      - name: data
        mountPath: /opt/render/project/src/server/data.db
        sizeGB: 1