services:
  - type: web
    name: weather-api
    env: node
    plan: free
    buildCommand: npm install --build-from-source
    startCommand: node server/index.js
    envVars:
      - key: NODE_VERSION
        value: 20.17.0
      - key: WEATHER_API_KEY
        value: 9dc47327f824116734111d9a56b9fbeb
      - key: PORT
        value: 5050
      - key: CACHE_TTL_CURRENT
        value: 600
      - key: CACHE_TTL_FORECAST
        value: 3600